# Site settings
title: mamaskitchen.de
email: mr-t@mamaskitchen.de
description: kochen, teilen, essen
baseurl: "/mamaskitchen.de"
url: "https://taitruong.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
